export const NIFTY_50 = [
  'ADANIENT', 'ADANIPORTS', 'APOLLOHOSP', 'ASIANPAINT', 'AXISBANK',
  'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BEL', 'BHARTIARTL',
  'BRITANNIA', 'CIPLA', 'COALINDIA', 'DRREDDY', 'EICHERMOT',
  'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO',
  'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'ITC', 'INDUSINDBK',
  'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M',
  'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC', 'POWERGRID',
  'RELIANCE', 'SBILIFE', 'SBIN', 'SHRIRAMFIN', 'SUNPHARMA',
  'TCS', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TECHM',
  'TITAN', 'TRENT', 'ULTRACEMCO', 'WIPRO'
];

export const SENSEX_30 = [
  'ASIANPAINT', 'AXISBANK', 'BAJFINANCE', 'BHARTIARTL', 'HCLTECH',
  'HDFCBANK', 'HINDUNILVR', 'ICICIBANK', 'INDUSINDBK', 'INFY',
  'ITC', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI',
  'NESTLEIND', 'NTPC', 'POWERGRID', 'RELIANCE', 'SBIN',
  'SUNPHARMA', 'TCS', 'TATAMOTORS', 'TATASTEEL', 'TECHM',
  'TITAN', 'ULTRACEMCO', 'ADANIPORTS', 'HINDALCO', 'JSWSTEEL'
];

export const NIFTY_NEXT_50 = [
  'ABB', 'ADANIENSOL', 'ADANIGREEN', 'AMBUJACEM', 'BANKBARODA',
  'BPCL', 'CANBK', 'CGPOWER', 'CHOLAFIN', 'DABUR',
  'DLF', 'DMART', 'DIVISLAB', 'GAIL', 'GODREJCP',
  'HAL', 'ICICIPRULI', 'INDIGO', 'INDUSTOWER', 'IOC',
  'IRCTC', 'JINDALSTEL', 'LICI', 'MOTHERSON', 'NAUKRI',
  'NHPC', 'PFC', 'PIDILITIND', 'PNB', 'RECLTD',
  'SIEMENS', 'TVSMOTOR', 'TORNTPHARM', 'VEDL', 'VOLTAS',
  'ZYDUSLIFE', 'HAVELLS', 'COLPAL', 'MARICO', 'MUTHOOTFIN',
  'OFSS', 'PAYTM', 'SAIL', 'SUPREMEIND', 'BOSCHLTD',
  'ADANIPOWER', 'UNIONBANK', 'PEL', 'LUPIN', 'AUROPHARMA'
];

export function getUniverse(group: string) {
  if (group === 'nifty50') return NIFTY_50;
  if (group === 'sensex30') return SENSEX_30;
  if (group === 'niftynext50') return NIFTY_NEXT_50;
  return Array.from(new Set([...NIFTY_50, ...SENSEX_30, ...NIFTY_NEXT_50]));
}